### ISSUE TITLE
Contain and compress dataset using cimx

### ISSUE THREAD

**Issue by Sveino** [3lbits/Grunnprofil#280]
Instance file (document) based on the 61970-series and 61968-13 (CDPSM) can be exchanged using the format/syntax defined in  [IEC 61970-552 CIMXML Model exchange format ](https://www.standard.no/no/Nettbutikk/produktkatalogen/Produktpresentasjon/?ProductID=851179).
There is also a plan to create a 61970-553 that describe the use of JSON-LD.
IEC 61970-600-1 describe how zip can be used for containing and compressing the CIMXML files. 
There have been some request to get a better way to contain information, avoid use of file naming-standards and provide providence and process based meta-data.

Related to #219 

This proposal is inspired by [Office Open XML File Formats specification](https://learn.microsoft.com/en-us/office/open-xml/open-xml-sdk)
In short this means that we create a [zip ](https://www.iana.org/assignments/media-types/application/zip) file that we give the file extension .cimx (similar to .docx). Renaming a .docx to zip we can unzip it and get the following structure:
![image](https://user-images.githubusercontent.com/15873106/214561526-4dedd1a5-e571-47fa-a3de-7f948f215cc0.png)

Suggest the following structure:
manifest.xml
manifest.jsonld
[Support] #(Asset, AssetCatalog, Customer)
[Support\CIMXML]
[Support\XML]
[Support\CIMJSON-LD]
[Grid]
[Grid\CIMXML]
[Grid\CIMJSON-LD]
[Market]
[Schedule]
[Schedule\[2022]  (Year)
[Schedule\[2022\01] (month)
[Schedule\[2022\01\12] (day)
[_rels] (providence)
[ReferenceData]
[ReferenceData\CIMXML]
[ReferenceData\CIMJSON-LD]
[Settings]
[Profile]
[Profile\Grid\v1\RDFXML]
[Profile\Grid\v2\RDFXML]
[Profile\Grid\v2\JSON-LD]
[Profile\Custom\ENTSO-E\v2\RDFXML]

**Comment by Sveino** [comment]
Compare zip and gzip: http://www.differencebetween.net/technology/difference-between-zip-and-gzip/

The file will not be that big. Less tha

**Comment by VladimirAlexiev** [comment]
Hi @Sveino ! cc @ar-chad

Office Open XML ([ECMA-376](https://www.ecma-international.org/publications-and-standards/standards/ecma-376), [ISO/IEC 29500:2016](https://www.iso.org/standard/71691.html), intro [OpenXML-White-Paper](https://ecma-international.org/wp-content/uploads/OpenXML-White-Paper.pdf)) has some features that make it less than ideal for CIM:
- It packages documents. Guess you can package other files, but it really is intended for document content (text and images)
- It's based on XML not RDF

Instead of it, I suggest to use Information Container for Linked Document Delivery (ICDD), ISO 21597. 
- It's a similar packaging format (zip with descriptor)
- but you can package any files, including RDF
- And the descriptor is in RDF
- Also, there is a specified "links" file (also RDF) that interlinks package contents

A great illustration from
[Using ICDD Containers for documentation data archives](https://chnt.at/wp-content/uploads/2022/09/ID091_GOEBELS.pdf): Semi-automated creation of linked documentation data archives using an Infor-mation Container for linked Document Delivery

<img width="1828" height="904" alt="Image" src="https://github.com/user-attachments/assets/b942005c-fbd6-46c5-9330-90c3615f1ec8" />

Originally it was designed to structure and exchange linked construction data, integrating with BIM (Building Information Modeling) to create transparent, traceable, and automated information workflows, especially within Common Data Environments (CDEs). It acts as a standardized "package" for project information, linking BIM elements (like IFC models) to authoritative documents using linked data principles, improving interoperability beyond proprietary formats for better lifecycle management and data continuity. 

But there's no obstacle to use it for electrical data. In fact, that would facilitate CIM-BIM integration.
So I think we should include a brief section in the upcoming paper.
